### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by project2dream** [KM8Oz/check_if_domain_parked#1]
is there a way to offload memory or take in less input? 32 gb ddr4
check_if_domain_parked-main\check_if_domain_parked-main\main.py", line 46, in <module>
    domain_names = generate_combinations(regex, legal_chars, tld, max_length)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\check_if_domain_parked-main\check_if_domain_parked-main\main.py", line 38, in generate_combinations
    all_possible_names.append(''.join(name))
MemoryError

**Comment by project2dream** [comment]
possible fix Write to File Directly:

Instead of storing all combinations in memory, write each generated combination directly to a file. This approach reduces memory consumption as the data is stored on disk instead of in RAM.
python
Copy code
def generate_combinations_and_write(regex, legal_chars, tld, max_length, file_path):
    with open(file_path, 'w') as file:
        for combination in some_combination_generator:
            file.write(combination + '\n')

**Comment by project2dream** [comment]
![image](https://github.com/KM8Oz/check_if_domain_parked/assets/105233383/c0638005-1724-4fc2-a6fa-bf31e849ec0f)
i got it to work but it generates this now lol

**Comment by KM8Oz** [comment]
fixed:
https://github.com/KM8Oz/check_if_domain_parked/commit/060e69c14dc256600d1e5d718c447f2cccd00b69

**Comment by KM8Oz** [comment]
leave me a star if it works for you

**Comment by KM8Oz** [comment]
regex is not a good idea, so I used simpler method with ? sign to generate combinations faster and get the real length

**Comment by project2dream** [comment]
> regex is not a good idea, so I used simpler method with ? sign to generate combinations faster and get the real length

do i re-download? im learning not very versatile yet.

**Comment by KM8Oz** [comment]
The pattern should be like casino?? .
If no ? It will check just one Wich is casino
Follow the documentation
